//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIDBMVCWEBSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Failed_Login_Attempts
    {
        public int AttemptsID { get; set; }
        public System.DateTime Dated { get; set; }
        public string Login { get; set; }
        public string IpAddress { get; set; }
        public int user_type_id { get; set; }
    }
}
