//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIDBMVCWEBSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLogOffUserDetail
    {
        public int LId { get; set; }
        public string Login { get; set; }
        public string IpAddress { get; set; }
        public Nullable<System.DateTime> DateOfLogin { get; set; }
        public Nullable<System.DateTime> DateOfLogOff { get; set; }
    }
}
