//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIDBMVCWEBSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class map_component_usertype
    {
        public int mpu { get; set; }
        public Nullable<int> ut_id { get; set; }
        public Nullable<int> comp_id { get; set; }
        public string status { get; set; }
        public Nullable<int> entryby { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
        public string ip_addr { get; set; }
    
        public virtual st_components st_components { get; set; }
        public virtual St_PermissionType St_PermissionType { get; set; }
    }
}
