//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIDBMVCWEBSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class permission
    {
        public int perm_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> comp_id { get; set; }
        public Nullable<int> mod_id { get; set; }
        public Nullable<int> add_perm { get; set; }
        public Nullable<int> mod_perm { get; set; }
        public Nullable<int> del_perm { get; set; }
        public Nullable<int> notappl { get; set; }
    
        public virtual SiteUser SiteUser { get; set; }
        public virtual st_components st_components { get; set; }
        public virtual st_module st_module { get; set; }
    }
}
