//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIDBMVCWEBSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteUser
    {
        public SiteUser()
        {
            this.permissions = new HashSet<permission>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public string Email { get; set; }
        public Nullable<int> User_Type_ID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string ContactNumber { get; set; }
        public string OrgnisationName { get; set; }
        public string SessionID { get; set; }
        public Nullable<int> EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string IpAddress { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Countryid { get; set; }
        public Nullable<int> FailureAttemptCount { get; set; }
    
        public virtual ICollection<permission> permissions { get; set; }
    }
}
