//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIDBMVCWEBSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_module
    {
        public st_module()
        {
            this.st_components = new HashSet<st_components>();
            this.permissions = new HashSet<permission>();
        }
    
        public int mod_id { get; set; }
        public string module_name { get; set; }
        public string status { get; set; }
        public Nullable<int> entry_by { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<int> pos { get; set; }
    
        public virtual ICollection<st_components> st_components { get; set; }
        public virtual ICollection<permission> permissions { get; set; }
    }
}
