//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIDBMVCWEBSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class St_PermissionType
    {
        public St_PermissionType()
        {
            this.map_component_usertype = new HashSet<map_component_usertype>();
        }
    
        public int PTypeID { get; set; }
        public string PType { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<map_component_usertype> map_component_usertype { get; set; }
    }
}
