//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIDBMVCWEBSITE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTrail
    {
        public int TrailID { get; set; }
        public int UserID { get; set; }
        public int user_type_id { get; set; }
        public string TableName { get; set; }
        public int LID { get; set; }
        public int ModuleID { get; set; }
        public System.DateTime Dated { get; set; }
        public string ActionTaken { get; set; }
        public string IpAddr { get; set; }
    }
}
